# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-30 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160430_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_info',
            name='teacher_info',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
