# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-30 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='sex',
            new_name='gender',
        ),
    ]
