# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-01 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160501_0307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='users',
            new_name='users_info',
        ),
    ]
